### PR TITLE
Eliminate the use of 'patmos-ar'

### PR DESCRIPTION
**Pull request by Emoun**
Removes all uses of `patmos-ar` and replaces it with `ar` (binutils), which should be already available on the machine.

`patmos-ar` is produced by the `patmos-gold` repository.
The handbook says `patmos-ar` has some special support for bitcode archives, but my understanding is that it is otherwise identical. Therefore, I'm beginning with simply removing use of `patmos-ar` where this special support doesn't seem needed.

Caveat: 
Since I don't know how the apps that use `patmos-ar` should behave, I cannot guarantee that they still work as expected. I have no idea how to test them (or simply don't have the hardware to) and the nightly test also doesn't use them. Therefore, please highlight this PR to any stakeholders before merging.

This is part of an effort to simplify the setup of the Patmos tool chain and as such remove the need for and use of `patmos-ar` across all T-CREST repositories.

### CODE REVIEW

**Comment by schoeberl** [comment]
Hi Emad,

why do you want to change this? We have the cross-compiler/linker/archiver tools for Patmos.
Why should we mix this with the host tools? By accident we had used the host ar at some time,
but that was broken on some host/compiler combination. Then we switched to the cross-compiler
tools (patmos-ar) to fix it.

End of line, I am against this change, as I do not see any benefit, but risks of compatibility
issues.

Cheers,
Martin

**Comment by Emoun** [comment]
As far as I can tell, `patmos-ar` is simply binutils `ar` compiled as part of the gold repository build but doesn't have any specialized code for Patmos. Additionally, `ar` is an architecture-independent tool/standard (as far as I can tell). Therefore, we shouldn't have to have our own port of it.

I'm trying to get my bearings around the whole tool chain. With this, I would also like to simplify as much as possible, to make future maintenance easier. The fewer artifacts we produce, the less work we have to do in the future. Therefore, wherever we can make use of standard versions of tools I think we should strive to do so.

If some host doesn't have the standard version of `ar`, I think that should be regarded as a problem with the host and not the Patmos tool chain. It would be the same as having a faulty version of GCC installed such that LLVM can't be compiled; should we also ship a custom version of GCC with the Patmos tool chain?

Could you say more about the compatibility issues you had? This change doesn't remove `patmos-ar`, just avoids using it. As far as I have been able to test, it works as expected. Though I would also prefer it some of you could test it out before merging. I would also like to point out that with this change (and a few similar changes to other repos), I can delete `patmos-ar` completely from my machine and the benchmark still runs successfully.

**Comment by schoeberl** [comment]
Hi Emad,

I understand you vision of removing target specific tools. However, I still think we should have all tools available in cross-platform version. There might be C++ compiler available that can compile our LLVM port, but not including ar. And as I wrote before: using the platform ar instead of patmos-ar was broken on one configuration. It was a former Bachelor student (Carsten Nielsen) who stumbled over this issue and fixed it for him by using the Patmos specific ar.

Sorry, but I am still not convinced that this simplification is worth the risk ;-)

Cheers,
Martin

**Comment by Emoun** [comment]
When was this? do you maybe know his github name so that I can have a look at his commits?

**Comment by schoeberl** [comment]
It was several years ago. The student was Carsten Nielson. He changed from ar to patmos-ar. However, I don’t think his particular configuration is so important. It jus shows that it is not a good idea to mix cross-compilation tools with hist tools.

Cheers,
Martin

**Pull request closed without merging**
