### PR TITLE
Pr/soundfx cop

### PR DESCRIPTION
**Pull request by 3picF4ilFTW**
Adds Audio Effects Coprocessor including benchmarks and benchmark results.
Moreover, updates SHA-256 benchmark results as well as README.

### CODE REVIEW

**Comment by schoeberl** [comment]
Do we really need to add all the results .txt file? I am not a big fan of adding generated files to a source repository.

**Comment by 3picF4ilFTW** [comment]
Well, I mostly did it to document the results since we do not report them in the corresponding paper.
But I agree with your point. I will remove them and push an update later today.

**Comment by 3picF4ilFTW** [comment]
Apologies, I forgot about the subdirectory. Should be better now.

**Comment by schoeberl** [comment]
Thanks for your contributions!

**Pull request merged**
